## Question 1: Checking Pandas and NumPy Versions

In [532]:
import numpy as np
import pandas as pd

print("Numpy Version:", np.__version__)
print("Pandas Version:", pd.__version__)

Numpy Version: 1.26.4
Pandas Version: 2.2.2


## Question 2: Print a String 10 Times

In [533]:
for _ in range(10):
    print("Hello BBC/BIT Year 3 AI Team")

Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team


## Question 3: Sum of Two Variables

In [534]:
a, b = 10, 20
sum_result = a + b
print("Sum:", sum_result)

Sum: 30


##  Question 4

(a) Define a Tuple with One Element

In [535]:
single_tuple = (5,)
print(single_tuple)

(5,)


(b) Print All Elements in a Tuple Using a Loop

In [536]:
my_tuple = (10, 20, 30, 40)
for item in my_tuple:
    print(item)

10
20
30
40


## Question 5: Creating a Dictionary

In [537]:
person = {"name": "Reagan’", "Phone": "+254 722 222333"}
print(person)

{'name': 'Reagan’', 'Phone': '+254 722 222333'}


##  Question 6: String Operations

In [538]:
s = "Almost Done with AI"

# a. The value of 3*x
print("3 * s:", 3 * s)

# b. The value of x[-1]
print("s[-1]:", s[-1]) #Last character

# c. The value of x[1]
print("s[1]:", s[1]) #Second the character

# d. The value of x[::2]
print("s[::2]:", s[::2]) #Every second character

3 * s: Almost Done with AIAlmost Done with AIAlmost Done with AI
s[-1]: I
s[1]: l
s[::2]: Ams oewt I


## Question 7: String Manipulation

In [539]:
import string

text = "BIT/BBC AI Comrades"

print("Upper =>", text.upper())
print("Lower =>", text.lower())
print("split =>", text.split())
print("join =>", "+".join(text.split()))
print("replace =>", text.replace("Python", "Java"))
print("find =>", text.find("python"), text.find("Java"))
print("count =>", text.count("n"))

Upper => BIT/BBC AI COMRADES
Lower => bit/bbc ai comrades
split => ['BIT/BBC', 'AI', 'Comrades']
join => BIT/BBC+AI+Comrades
replace => BIT/BBC AI Comrades
find => -1 -1
count => 0


## Question 9: Print Numbers Using Loops

In [540]:
# a. Print numbers 0 to 100
for i in range(101):
    print(i, end=" ")
    
# b. Print numbers 0 to 100 divisible by 7
print("\nNumbers divisible bt 7:", [i for i in range(101) if i % 7 == 0])

# c. Numbers divisible by 5 but not 3
print("\nNumbers divisible by 5 but not 3:", [i for i in range(1, 101) if i % 5 == 0 and i % 3 != 0])

# d. Print divisors (excluding 1 and itself)
for  x in range(2,21):
    print(f"Divisors of {x}:", [i for i in range(2, x) if x % i == 0])

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 
Numbers divisible bt 7: [0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]

Numbers divisible by 5 but not 3: [5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]
Divisors of 2: []
Divisors of 3: []
Divisors of 4: [2]
Divisors of 5: []
Divisors of 6: [2, 3]
Divisors of 7: []
Divisors of 8: [2, 4]
Divisors of 9: [3]
Divisors of 10: [2, 5]
Divisors of 11: []
Divisors of 12: [2, 3, 4, 6]
Divisors of 13: []
Divisors of 14: [2, 7]
Divisors of 15: [3, 5]
Divisors of 16: [2, 4, 8]
Divisors of 17: []
Divisors of 18: [2, 3, 6, 9]
Divisors of 19: []
Divisors of 20: [2, 4, 5, 10]


## Question 10

(a) Multiplication Function

In [541]:
def multiplication(a, b):
    return a * b

print(multiplication(8, 6)) #Outputs 48

48


(b) Square of Product Function

In [542]:
def sqrProd(x, y):
    return (x * y) ** 2

print(sqrProd(2, 5)) #Output: 100

100


## Question 11: NumPy Operations

In [543]:
import numpy as np

# (a) Create a 5X5 array of zeros
arr_zeros = np.zeros((5, 5))
print(arr_zeros)
print("\n")

# (b) Create a 3X3 matrix with values from 0 to 8
matrix_3X3 = np.arange(9).reshape(3, 3)
print(matrix_3X3)
print("\n")

# (c) Find indices of non-zero elements
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print("Non-zero indices:", non_zero_indices)
print("\n")

# (d) Create a 10X10 random array and find min/max
rand_matrix = np.random.rand(10, 10)
#print(rand_matrix)
print("Min:", rand_matrix.min(), "Max:", rand_matrix.max())
print("\n")

# (e) Create a random vector of size 30 and find mean
rand_vector = np.random.rand(30)
print(rand_vector)
print("Mean:", rand_vector.mean())
print("\n")

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Non-zero indices: (array([0, 1, 4], dtype=int64),)


Min: 0.006709498559738125 Max: 0.987664167307276


[0.36251894 0.9820689  0.14842079 0.09425862 0.87067817 0.10790964
 0.40911628 0.24456168 0.31814192 0.52069945 0.02060931 0.1104172
 0.91271548 0.54016543 0.20654145 0.98363233 0.54934479 0.82675562
 0.8378146  0.0392503  0.65385869 0.97894609 0.94363456 0.56627668
 0.27840001 0.96988791 0.37585355 0.04915235 0.70814421 0.53745066]
Mean: 0.5049075209826126




## Question 12: User Input for Math Operations

In [ ]:
a = int(input("Enter first number: "))
b= int(input("Enter second number: "))

print("Sum: ", a + b)
print("Product: ", a* b)
print("Diffrence: ", a - b)
print("Quotient: ", a /b if b != 0 else "Cannot divide bt zero")

Sum:  30
Product:  200
Diffrence:  -10
Quotient:  0.5


## Question 13

(a) Function to Double List Elements

In [545]:
def doubleList(numberList):
    for num in numberList:
        print(num * 2)
        
doubleList([3, 1, 5]) #Outputs 6, 2, 10

6
2
10


(b) Polynomial Evaluation

In [546]:
def polynomial(x):
    return 3 * (x ** 2) - x + 2

print(polynomial(3)) #Outputs: 26

26


(c) Maximum Function Without max()

In [547]:
#Using if-else
def my_max(x, y):
    if x > y:
        return x
    else:
        return y
    
    
#Using only if
def my_max_if(x, y):
    if x > y:
        return x
    return y

print(my_max(10, 20)) #Output: 20
print(my_max_if(10, 20)) #Ouput: 20


20
20


(d) Area and Circumference of a Circle

In [548]:
import math

def area(radius):
    return math.pi * radius ** 2

def circum(radius):
    return 2 * math.pi * radius

#r = float(input("Enter the radius of the circle: "))
print("Area: ", area(r))
print("Circumfrence:", circum(r))

Area:  153.93804002589985
Circumfrence: 43.982297150257104


## Question 14: Object-Oriented Programming (OOP)

(a) Vehicle Class

In [549]:
class Vehicle:
    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage
        
car = Vehicle(240, 10000)        
print(f"Max Speed: {car.max_speed} Km/h, Mileage: {car.mileage} Km")

Max Speed: 240 Km/h, Mileage: 10000 Km


(b) Bus Class (Inheritance)

In [550]:
class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage):
        super().__init__(max_speed, mileage)
        self.name = name
        
bus = Bus("School Mercedes", 180, 1000)
print(f"Name: {bus.name}, Max Speed: {bus.max_speed}, Mileage: {bus.mileage}")

Name: School Mercedes, Max Speed: 180, Mileage: 1000


(c) Bus with Default Seating Capacity

In [551]:
class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage, seating_capacity=50):
        super().__init__(max_speed, mileage)
        self.name = name
        self.seating_capacity = seating_capacity
        
bus = Bus("School Mercedes", 180, 1000)
print(f"Seating Capacity: {bus.seating_capacity}")

Seating Capacity: 50


(d) Default Color Attribute

In [552]:
class Vehicle:
    color = "White"
    
car = Vehicle()
print("Vehicle Color:", car.color)

Vehicle Color: White
